export const vintagedb = [
    {
        id : 1,
        name : "Modern Shell Chair",
        price : 208.00,
        quantity : 1,
        description : "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
        image_1 : "https://i.ibb.co/rkyV4gZ/product-classic-chair-3.jpg",
        image_2 : "https://i.ibb.co/pypvmn9/product-classic-chair.jpg",
        image_3 : "https://i.ibb.co/T15zWSS/product-classic-chair-2.jpg",
    },
    {
        id : 2,
        name : "Modern Shell Chair",
        price : 208.00,
        quantity : 1,
        description : "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
        image_1 : "https://i.ibb.co/rkyV4gZ/product-classic-chair-3.jpg",
        image_2 : "https://i.ibb.co/pypvmn9/product-classic-chair.jpg",
        image_3 : "https://i.ibb.co/T15zWSS/product-classic-chair-2.jpg",
    },
    {
        id : 3,
        name : "Modern Shell Chair",
        price : 208.00,
        quantity : 1,
        description : "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
        image_1 : "https://i.ibb.co/rkyV4gZ/product-classic-chair-3.jpg",
        image_2 : "https://i.ibb.co/pypvmn9/product-classic-chair.jpg",
        image_3 : "https://i.ibb.co/T15zWSS/product-classic-chair-2.jpg",
    },
    {
        id : 4,
        name : "Modern Shell Chair",
        price : 208.00,
        quantity : 1,
        description : "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
        image_1 : "https://i.ibb.co/rkyV4gZ/product-classic-chair-3.jpg",
        image_2 : "https://i.ibb.co/pypvmn9/product-classic-chair.jpg",
        image_3 : "https://i.ibb.co/T15zWSS/product-classic-chair-2.jpg",
    },
    {
        id : 5,
        name : "Modern Shell Chair",
        price : 208.00,
        quantity : 1,
        description : "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
        image_1 : "https://i.ibb.co/rkyV4gZ/product-classic-chair-3.jpg",
        image_2 : "https://i.ibb.co/pypvmn9/product-classic-chair.jpg",
        image_3 : "https://i.ibb.co/T15zWSS/product-classic-chair-2.jpg",
    },
    {
        id : 6,
        name : "Modern Shell Chair",
        price : 208.00,
        quantity : 1,
        description : "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
        image_1 : "https://i.ibb.co/rkyV4gZ/product-classic-chair-3.jpg",
        image_2 : "https://i.ibb.co/pypvmn9/product-classic-chair.jpg",
        image_3 : "https://i.ibb.co/T15zWSS/product-classic-chair-2.jpg",
    },
    {
        id : 7,
        name : "Modern Shell Chair",
        price : 208.00,
        quantity : 1,
        description : "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
        image_1 : "https://i.ibb.co/rkyV4gZ/product-classic-chair-3.jpg",
        image_2 : "https://i.ibb.co/pypvmn9/product-classic-chair.jpg",
        image_3 : "https://i.ibb.co/T15zWSS/product-classic-chair-2.jpg",
    },
    {
        id : 8,
        name : "Modern Shell Chair",
        price : 208.00,
        quantity : 1,
        description : "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
        image_1 : "https://i.ibb.co/rkyV4gZ/product-classic-chair-3.jpg",
        image_2 : "https://i.ibb.co/pypvmn9/product-classic-chair.jpg",
        image_3 : "https://i.ibb.co/T15zWSS/product-classic-chair-2.jpg",
    },
];